name: Publish Plugin

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Plugin
        run: ./gradlew buildPlugin

      - name: Publish to JetBrains Marketplace
        uses: CodingWithCalvin/GHA-JBMarketplacePublisher@v1
        with:
          marketplace-pat: ${{ secrets.MARKETPLACE_PAT }}
          plugin-id: 27391
          archive-path: "build/distributions/*.zip"
